---
- name: DÃ©sinstaller plusieurs paquets APT
  apt:
    name:
      - korganizer
      - dragonplayer
      - juk
      - kaddressbook
      - kmail
      - kmailtransport-plugins
      - pim-sieve-editor
      - pim-data-exporter
      - kwrite
      - kmouth
      - kmousetool
    state: absent
    purge: yes